hr/urls.py
from django.urls import path
from hr import views
from django.conf import settings
from django.conf.urls.static import static

#general urls
app_name = 'hr'

""" URLs used in the HR application. """
urlpatterns = [
    path('recruitment/', views.RecruitmentView.as_view(), name='recruitment'),
    path('jobDescription/', views.JobDescriptionView.as_view(), name='jobDescription'),
    path('approveRequest/', views.ApproveRequestView.as_view(), name='approveRequest'),
    path('requestList/', views.RequestListView.as_view(), name='requestList'),
    path('jobVacancy/', views.JobVacancyAdvertisementView.as_view(), name='jobVacancy'),
    path('receiveCVs/', views.ReceiveCVsView.as_view(), name='receiveCV'),

    

]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import View
from . import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'user'
urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(),name='login'),
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup' ),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update' ),
    path(route='<str:username>/', view=views.UserDetailView.as_view(), name='detail' ),
]

if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Person(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name = _('User'),
        null=True,
        blank=True, 
        on_delete=models.CASCADE,
        help_text=_("Enter a user name"))
    cc = models.CharField(
        verbose_name = _('CC'),
        max_length=11, 
        blank=True, 
        help_text=_("Enter your ID number"))
    name = models.CharField(
        verbose_name = _('Name'),
        max_length=50, 
        blank=True, 
        help_text=_("Enter your name"))
    lastName = models.CharField(
        verbose_name = _('Last name'),
        max_length=50, 
        blank=True, 
        help_text=_("Enter your last name"))
    email = models.CharField(
        verbose_name = _('E-mail'),
        max_length=100, 
        blank=True, 
        help_text=_("Enter your e-mail"))
    cv = models.FileField(
        verbose_name = _('CVs'),
        blank=True,
        upload_to='CVs'
    )
    cellphone = models.CharField(
        verbose_name = _('Cellphone'),
        max_length=11, 
        blank=True, 
        help_text=_("Enter your cell phone number"))
    home_address = models.CharField(
        verbose_name = _('Home address'),
        max_length=150, 
        blank=True, 
        help_text=_("Enter your home address"))
    Age=models.IntegerField(
        verbose_name = _('Age'),
        default=0,
        help_text=_("Enter your Age"))

    def __str__(self):
        return self.name +" "+ self.lastName 

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('Persons') 

user/forms.py
from django import forms
from user.models import Person
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(label = _('Username'), min_length=4, max_length=50)

    password = forms.CharField(
        label = _('Password'), 
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        label = _('Password confirmation'), 
        max_length=70,
        widget=forms.PasswordInput()
    )

    # first_name = forms.CharField(label = _('First name'), min_length=2, max_length=50)
    # last_name = forms.CharField(label = _('Last name'), min_length=2, max_length=50)

    email = forms.CharField(
        label = _('Email'), 
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError(_('Username is already in use.'))
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError(_('Passwords do not match.'))

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Person(user=user)
        profile.save()

user/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from shop.models import Order, OrderItem
from user.models import Person

# Forms
from user.forms import SignupForm
# Create your views here.


class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = 'login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'logged_out.html'

class UserDetailView(LoginRequiredMixin, UpdateView):
    """User detail view."""

    template_name = 'detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    

    model = Person
    fields = ['name', 'lastName', 'cc', 'email', 'cellphone',  'home_address', 'Age']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.person

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('user:detail', kwargs={'username': username})
    
    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context.update({
            "orders": Order.objects.filter(user=self.request.user, ordered=True)
        })
        return context


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()        
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'update_profile.html'
    model = Person
    fields = ['name', 'lastName', 'cc', 'email', 'cellphone',  'home_address', 'Age']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.person

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('user:detail', kwargs={'username': username})

user/templates/detail.html
{% extends "home.html" %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %}
    {% trans "My account" %}
{% endblock %}

{% block content %}

<div id="content" class="bg-white m-3 p-3">
    <div class="container ">
      <div class="row bar">
        <div id="customer-account" class="col-lg-9 clearfix">
            <h3 class="text-uppercase">@{{ request.user.username}} | {{person.name}} {{person.lastName}}</h3> 
            <hr>
            <div class="bo3">
                <div class="heading">
                  <h3 class="text-uppercase">{% trans "Personal details" %}</h3>
                </div>
                <form action="{% url 'user:detail' request.user.username %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "Name" %}</label>
                                <input
                                    class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="name"
                                    placeholder="{% trans 'Enter your name' %}"
                                    value="{% if form.errors %}{{ form.name.value }}{% else %}{{ person.name }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "Last Name" %}</label>
                                <input
                                    class="form-control {% if form.lastName.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="lastName"
                                    placeholder="{% trans 'Enter your last name' %}"
                                    value="{% if form.errors %}{{ form.lastName.value }}{% else %}{{ person.lastName }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.lastName.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "E-mail" %}</label>
                                <input
                                    class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="email"
                                    placeholder="{% trans 'Enter your E-mail' %}"
                                    value="{% if form.errors %}{{ form.email.value }}{% else %}{{ person.email }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "Age" %}</label>
                                <input
                                    class="form-control {% if form.Age.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="Age"
                                    placeholder="{% trans 'Enter your age' %}"
                                    value="{% if form.errors %}{{ form.Age.value }}{% else %}{{ person.Age }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.Age.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="firstname">{% trans "Identification Card" %}</label>
                                <input
                                    class="form-control {% if form.cc.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="cc"
                                    placeholder="{% trans 'Enter your ID number' %}"
                                    value="{% if form.errors %}{{ form.cc.value }}{% else %}{{ person.cc }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.cc.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "Phone number" %}</label>
                                <input
                                    class="form-control {% if form.cellphone.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="cellphone"
                                    placeholder="{% trans 'Enter your cell phone number' %}"
                                    value="{% if form.errors %}{{ form.cellphone.value }}{% else %}{{ person.cellphone }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.cellphone.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{% trans "Address" %}</label>
                                <input
                                    class="form-control {% if form.home_address.errors %}is-invalid{% endif %}"
                                    type="text"
                                    name="home_address"
                                    placeholder="{% trans 'Enter your home address' %}"
                                    value="{% if form.errors %}{{ form.home_address.value }}{% else %}{{ person.home_address }}{% endif %}"
                                />
                                <div class="invalid-feedback">
                                    {% for error in form.address.errors %}
                                        {{ error }}
                                    {% endfor%}
                                </div>
                            </div>
                        </div>
                    </div>              
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-template-outlined"><i class="fa fa-save"></i>{% trans "Save changes" %}</button>
                    </div>              
                </form>
            </div>
            <div class="box mt-5">
                <div class="heading">
                  <h3 class="text-uppercase">{% trans "Your Orders" %}</h3>
                </div>
                <div class="site-blocks-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{% trans "Reference No." %}</th>
                                <th>{% trans "Date" %}</th>
                                <th>{% trans "Amount" %}</th>
                                <th>{% trans "Payment Status" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <a href="#"><td>#{{ order.reference_number }}</td></a>
                                <td>{{ order.ordered_date }}</td>
                                <td>{{ order.get_total }}</td>
                                <td>{% if order.ordered %}{% trans "Paid" %}{% else %}{% trans "Not paid" %}{% endif %}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="4">{% trans "You haven't made any purchases" %}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 mt-4 mt-lg-0">
          <!-- CUSTOMER MENU -->
          <div class="panel panel-default sidebar-menu">
            <div class="panel-heading">
              <h3 class="h4 panel-title">{% trans "Customer section" %}</h3>
            </div>
            <div class="panel-body">
              <ul class="nav nav-pills flex-column text-sm">
                <li class="nav-item">
                    <a href="#" class="nav-link ">
                        <i class="fa fa-sliders"></i>
                        {% trans "Settings" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:detail' request.user.username %}" class="nav-link">
                        <i class="fa fa-user"></i>
                        {% trans "My account" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:logout' %}" class="nav-link">
                        <i class="fa fa-sign-out"></i>
                        {% trans "Logout" %}
                    </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

user/templates/login.html
{% extends "home.html" %}
{% load i18n%}
{% block title %}
    {% trans "Login" %}
{%endblock%}


{% block content %}
  
    <div class="site-section m-3 p-3" id="content">
        <div class="container bg-white">
            <div class="row justify-content-center align-items-center minh-100">               
                <div class="col-lg-6">
                    <div class="box">
                        <h2 class="text-uppercase">{% trans "Login" %}</h2>                        
                        <hr>
                        <form method="POST" action= "{% url 'user:login' %}" >
                            {% csrf_token %}
    
                            <div class="form-group " >
                                {% if form.error_messages %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss = "alert" aria-label = "Close">
                                        <span aria-hidden = "true">&times;</span>
                                        </button>
                                        <strong>{% trans "Warning" %}: </strong> {{ form.get_invalid_login_error }}
                                    </div>
                                {% endif %}

                                <input class="form-control" type="text" placeholder="{% trans 'Username' %}" name="username" style="max-width: 500px;"/>
                            </div>
    
                            <div class="form-group">
                                <input class="form-control" type="password" placeholder="{% trans 'Password' %}" name="password" style="max-width: 500px;" />
                            </div>    
                            <button class="btn btn-template-outlined btn-block mt-5" type="submit" style="max-width: 500px;"><i class="fa fa-sign-in"></i>{% trans "Sign in" %}!</button>                           
                        </form> 
                       <p class="text-center text-muted">{% trans "Not registered yet?" %}</p>
                       <p class="mt-4">
                          <a href="#"><strong>{% trans "Register now" %}</strong></a>
                          ! {% trans "It is easy and done in 1 minute and gives you access to special discounts and much more" %}!                    
                        </p>                      
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/signup.html
{% extends "home.html" %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %}
    {% trans "Sign Up" %}
{% endblock %}

{% block content %}
    <div id="content" class="p-3">
        <div class="container bg-white">
            <div class="row">
                <div class="col-lg-6">
                    <div class="box">
                        <h2 class="text-uppercase">{% trans "New account" %}</h2>
                        <hr>
                        <form action="{% url 'user:signup' %}" method="POST">
                            {% csrf_token %}
                            {{ form |crispy }}                  
                            <button class="btn btn-template-outlined btn-block mt-5" type="submit">{% trans "Register" %}!</button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="box">
                        <h2 class="text-uppercase">{% trans "Login" %}</h2>
                        <hr>
                        <form method="POST" action= "{% url 'user:login' %}" >
                            {% csrf_token %}
    
                            <div class="form-group " >
                                {% if form.error_messages %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss = "alert" aria-label = "Close">
                                        <span aria-hidden = "true">&times;</span>
                                        </button>
                                        <strong>{% trans "Warning" %}: </strong> {{ form.get_invalid_login_error }}
                                    </div>
                                {% endif %}

                                <input class="form-control" type="text" placeholder="{% trans 'Username' %}" name="username" style="max-width: 500px;"/>
                            </div>
    
                            <div class="form-group">
                                <input class="form-control" type="password" placeholder="{% trans 'Password' %}" name="password" style="max-width: 500px;" />
                            </div>    
                            <button class="btn btn-template-outlined btn-block mt-5" type="submit" style="max-width: 500px;"><i class="fa fa-sign-in"></i> {% trans "Sign in" %}!</button>                           
                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/update_profile.html
{% extends "home.html" %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %}
    {% trans "Personal data" %}
{% endblock %}

{% block content %}

<div class="site-section m-3 p-3">
    <div class="container bg-white">
        <div class="row justify-content-md-center">
            <div class="col-6 p-4" id="profile-box">
                <form action="{% url 'user:update' %}" method="POST" >
                    {% csrf_token %}
                    <div class="media">                   
                        <div class="media-body">
                            <h5 class="ml-4">@{{ user.username }} | {{person.name}} {{person.lastName}}</h5>                        
                        </div>
                    </div>                
                    <hr><br>
                    {# Name  field #}
                    <div class="form-group">
                        <label>{% trans "Name" %}</label>
                        <input
                            class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                            type="text"
                            name="name"
                            placeholder="{% trans 'Enter your name' %}"
                            value="{% if form.errors %}{{ form.name.value }}{% else %}{{ person.name }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>
                    {# Last Name  field #}
                    <div class="form-group">
                        <label>{% trans "Last Name" %}</label>
                        <input
                            class="form-control {% if form.lastName.errors %}is-invalid{% endif %}"
                            type="text"
                            name="lastName"
                            placeholder="{% trans 'Enter your last name' %}"
                            value="{% if form.errors %}{{ form.lastName.value }}{% else %}{{ person.lastName }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.lastName.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>  
                    {# Identification Card  field #}
                    <div class="form-group">
                        <label>{% trans "Identification Card" %}</label>
                        <input
                            class="form-control {% if form.cc.errors %}is-invalid{% endif %}"
                            type="text"
                            name="cc"
                            placeholder="{% trans 'Enter your ID number' %}"
                            value="{% if form.errors %}{{ form.cc.value }}{% else %}{{ person.cc }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.cc.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>
                    {# E-mail  field #}
                    <div class="form-group">
                        <label>{% trans "E-mail" %}</label>
                        <input
                            class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                            type="text"
                            name="email"
                            placeholder="{% trans 'Enter your e-mail' %}"
                            value="{% if form.errors %}{{ form.email.value }}{% else %}{{ person.email }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>               
                    {# Phone number field #}
                    <div class="form-group">
                        <label>{% trans "Phone number" %}</label>
                        <input
                            class="form-control {% if form.cellphone.errors %}is-invalid{% endif %}"
                            type="text"
                            name="cellphone"
                            placeholder="{% trans 'Enter your cell phone number' %}"
                            value="{% if form.errors %}{{ form.cellphone.value }}{% else %}{{ person.cellphone }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.cellphone.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>
    
                    {# Address field #}
                    <div class="form-group">
                        <label>{% trans "Address" %}</label>
                        <input
                            class="form-control {% if form.home_address.errors %}is-invalid{% endif %}"
                            type="text"
                            name="home_address"
                            placeholder="{% trans 'Enter your home address' %}"
                            value="{% if form.errors %}{{ form.home_address.value }}{% else %}{{ person.home_address }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>
    
                    {# Age field #}
                    <div class="form-group">
                        <label>{% trans "Age" %}</label>
                        <input
                            class="form-control {% if form.Age.errors %}is-invalid{% endif %}"
                            type="text"
                            name="Age"
                            placeholder="{% trans 'Enter your Age' %}"
                            value="{% if form.errors %}{{ form.Age.value }}{% else %}{{ person.Age }}{% endif %}"
                        />
                        <div class="invalid-feedback">
                            {% for error in form.Age.errors %}
                                {{ error }}
                            {% endfor%}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mt-5">{% trans "Update info" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}