hr/urls.py
from django.urls import path
from hr import views
from django.conf import settings
from django.conf.urls.static import static

#general urls
app_name = 'hr'

""" URLs used in the HR application. """
urlpatterns = [
    path('recruitment/', views.RecruitmentView.as_view(), name='recruitment'),
    path('jobDescription/', views.JobDescriptionView.as_view(), name='jobDescription'),
    path('approveRequest/', views.ApproveRequestView.as_view(), name='approveRequest'),
    path('requestList/', views.RequestListView.as_view(), name='requestList'),
    path('jobVacancy/', views.JobVacancyAdvertisementView.as_view(), name='jobVacancy'),
    path('receiveCVs/', views.ReceiveCVsView.as_view(), name='receiveCV'),

    

]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Interview(models.Model):
    interviewDate = models.DateField(
        verbose_name = _('Inteview date'),
        help_text=_("Enter the interview date "))
    interviewFile = models.CharField(
        verbose_name = _('Interview file'),
        max_length=250,
        help_text=_("Add interview file"))
    interviewPerformance = models.BooleanField(
        verbose_name = _('Interview performance'),
        default = False,
        help_text=_("Interview performance OK?"))
    interviewResults = models.CharField(
        verbose_name = _('Interview results'),
        max_length=250,
        help_text=_("Enter the interview results"))
    location = models.CharField(
        verbose_name = _('Location'),
        max_length=250,
        help_text=_("Enter Location"))

    class Meta:
        verbose_name = _('Interview')
        verbose_name_plural = _('Interviews')

class Area(models.Model):
    """
    In this model the departments/Area that the organization owns are created.
    """

    areaName = models.CharField(
        verbose_name = _('Area name'),
        max_length=250, 
        help_text=_("Department/Area name"))
    areaDescription = models.CharField(
        verbose_name = _('Area description'),
        max_length=500, 
        help_text=_("Description of the department/area"))
    areaCode = models.CharField(
        verbose_name = _('Area Code'),
        max_length=250, 
        help_text=_("Department/Area code"))

    class Meta:
        verbose_name = _('Area')
        verbose_name_plural = _('Areas')

    def __str__(self):
        """Return area name"""
        return self.areaName

class JobDescription(models.Model):
    """
    In this model the job descriptions to be used for recruitments are created.

    Stores a Job Description entry, related to :model:`auth.User` and :model:`hr.Area`.  
    """

    createdBy = models.ForeignKey(
        User,
        verbose_name = _('Created by'),
        null=False, 
        on_delete=models.CASCADE,
        help_text=_("User creating the job description"))
    creationDate = models.DateField(
        verbose_name = _('Creation date'),
        help_text=_("Creation date for job description"))
    code = models.CharField(
        verbose_name = _('Code'),
        max_length=250, 
        help_text=_("ID of the job description"))
    title = models.CharField(
        verbose_name = _('Title'),
        max_length=250, 
        help_text=_("Title/name of the job description"))
    departament = models.ForeignKey(
        Area,
        null=False,
        on_delete=models.CASCADE,  
        verbose_name = _('Departament'),
        help_text=_("Department/Area associated with the job description"))
    reportTo = models.CharField(
        verbose_name = _('Report to'),
        max_length=250, 
        help_text=_("Immediate supervisor associated with the job description"))
    jobDescription = models.CharField(
        verbose_name = _('Job description'),
        max_length=500, 
        help_text=_("Job description"))
    responsabilities = models.CharField(
        verbose_name = _('Responsabilities'),
        max_length=500, 
        help_text=_("Job functions"))
    skills = models.CharField(
        verbose_name = _('Skills'),
        max_length=500, 
        help_text=_("The capacities to perform tasks that you are developed"))
    abilities = models.CharField(
        verbose_name = _('Abilities'),
        max_length=250,
        help_text=_("Talents you are born with."))
    experience = models.CharField(
        verbose_name = _('Experience'),
        max_length=250,
        help_text=_("Time of experience on the job"))
    educationRequirements = models.CharField(
        verbose_name = _('Education requirements'),
        max_length=250,
        help_text=_("Level of education required"))
    knowledge = models.CharField(
        verbose_name = _('Knowledge'),
        max_length=250,
        help_text=_("Knowledge required for the job"))
    annualSalary = models.DecimalField(
        verbose_name = _('Annual salary'), 
        default = 0,
        decimal_places = 2,
        max_digits = 11,
        help_text=_("Approximate annual salary"))

    class Meta:
        verbose_name = _('Job description')
        verbose_name_plural = _('Job descriptions')

    def __str__(self):
        """Return code job description"""
        return self.code

class Recruitment(models.Model):
    """  
    Recruitment applications are created in this model.
    
    Stores a Recruitment entry, related to :model:`auth.User`, :model:`hr.JobDescription` and :model:`hr.Area`. 
    """

    requester = models.ForeignKey(
        User,
        verbose_name = _('Requester'),
        null=False, 
        on_delete=models.CASCADE,
        help_text=_("User who created the request"))
    dateOfRequest = models.DateField(
        verbose_name = _('Date of request'),
        help_text=_("Date of recruitment request"))
    departament = models.ForeignKey(
        Area,
        null=False,
        on_delete=models.CASCADE,
        verbose_name = _('Departament'),
        help_text=_("Department/Area that require the recruitment"))
    jobDescription = models.ForeignKey(
        JobDescription,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name = _('Job description'),
        help_text=_("Associated job description"))
    startingDate = models.DateField(
        verbose_name = _('Starting date'),
        help_text=_("Start date of the job"))
    numberOfVacancies = models.PositiveIntegerField(
        verbose_name = _('Number of vacancies'),
        help_text=_("Number of vacancies available"))
    title = models.CharField(
        verbose_name = _('Title'),
        max_length=250, 
        help_text=_("Name of vacancy"))
    responsabilities = models.CharField(
        verbose_name = _('Responsabilities'),
        max_length=500, 
        help_text=_("Job functions"))
    location = models.CharField(
        verbose_name = _('Location'),
        max_length=250, 
        help_text=_("Work location"))
    comments = models.CharField(
        verbose_name = _('Comments'),
        blank=True,
        max_length=500, 
        help_text=_("A maximum of 500 characters is allowed"))
    requisitionApproved = models.BooleanField(
        verbose_name = _('Requisition approved'), 
        default=False,
        help_text=_("Requisition Approved?"))
    approvalsComments = models.CharField(
        verbose_name = _('Approvals comments'),
        blank=True,
        max_length=500, 
        help_text=_("A maximum of 500 characters is allowed"))

    class Meta:
        verbose_name = _('Recruitment')
        verbose_name_plural = _('recruitments')

    def __str__(self):
        """Return title of recruitment"""
        return self.title

class Advertisement(models.Model):
    """
    Model to obtain the data that will be used to generate the advertising of the vacancies. 
    """
    closingDate = models.DateField(
        verbose_name = _('Closing date'),
        help_text=_("Closing date for advertisement"))
    companyDescription = models.CharField(
        verbose_name = _('Company description'),
        max_length=500,
        help_text=_("Short description of the company"))
    contactDetails = models.CharField(
        verbose_name = _('Contact details'),
        max_length=250,
        help_text=_("The necessary information to contact the candidate"))
    idealCandidate= models.CharField(
        verbose_name = _('Ideal candidate'),
        max_length=250,
        help_text=_("The characteristics of the ideal candidate"))
    jobDescription = models.CharField(
        verbose_name = _('Job description'),
        max_length=500,
        help_text=_("Characteristics that describe the vacancy ")) 
    jobTitle = models.CharField(
        verbose_name = _('Job title'),
        max_length=250,
        help_text=_("Name of the vacancy"))
    location = models.CharField(
        verbose_name = _('Location'),
        max_length=250,
        help_text=_("Location of the vacancy"))
    salaryGuide = models.CharField(
        verbose_name = _('Salary guide'),
        max_length=250,
        help_text=_("Characteristics such as experience that help establish the salary"))
    comments = models.CharField(
        verbose_name = _('Comments'),
        max_length=500,
        help_text=_("Comment here some additional features to consider"))
    advertisementType = models.BooleanField(
        verbose_name = _('Advertisement type'),
        default = False,
        help_text=_("Internal or External?"))

    class Meta:
        verbose_name = _('Advertisement')
        verbose_name_plural = _('Advertisements')

    def __str__(self):
        """Return job title of advertisement"""
        return self.jobTitle

hr/forms.py
from tabnanny import verbose
from tkinter import Widget
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from user.models import Person

from .models import JobDescription, Recruitment

class AddJobDescriptionForm(forms.ModelForm):
    """ Form creation - AddJobDescription Form """

    class Meta:
        """ AddJobDescription Form Inherits from the JobDescription model. """

        model = JobDescription
        fields = [
            _('createdBy'), 
            _('creationDate'), 
            _('code'),
            _('title'), 
            _('departament'), 
            _('reportTo'),
            _('jobDescription'), 
            _('responsabilities'), 
            _('skills'),
            _('abilities'),
            _('experience'),
            _('educationRequirements'),
            _('knowledge'),
            _('annualSalary')]
        help_texts = {'': None,}
        verbose_name = [
            _('Created by'), 
            _('Creation date'), 
            _('Code'), 
            _('Title'), 
            _('Departament'),
            _('Report to'),
            _('Job description'),
            _('Responsabilities'),
            _('Skills'),
            _('Abilities'),
            _('Experience'),
            _('Education requirements'),
            _('Knowledge'),
            _('Annual salary')]

class AddRecruitmentForm(forms.ModelForm):
    """ Form creation - AddRecruitment Form """
    
    class Meta:
        """ AddRecruitment Form Inherits from the Recruitment model. """

        model = Recruitment
        fields = [
            _('requester'), 
            _('dateOfRequest'), 
            _('departament'), 
            _('jobDescription'),
            _('startingDate'),
            _('numberOfVacancies'),
            _('title'),
            _('responsabilities'),
            _('location'),
            _('comments')]
        help_texts = {'requester': None,}
        verbose_name = [
            _('Requester'),
            _('Date of request'),
            _('Departament'),
            _('Job description'),
            _('Starting date'),
            _('Number of vacancies'),
            _('Title'),
            _('Responsabilities'),
            _('Location'),
            _('Comments')]

class ApproveRequestForm(forms.Form):
    """ Form creation - ApproveRequest Form """

    """ Options for RequisitionApproved field in the AddRecruitment Form. """
    REQUISITION_APPROVED_CHOICES = [
        ('True', _('Yes')),
        ('False', 'No'),
    ]   

    requisitionApproved = forms.ChoiceField(
        label = _('Requisition approved'),
        required = True, 
        widget = forms.RadioSelect,
        choices = REQUISITION_APPROVED_CHOICES,
    )
    approvalsComments = forms.CharField(
        label = _('Approvals comments'),
        max_length=500,
        required=False, 
        widget=forms.Textarea(attrs={ 'placeholder': _("Approvals comments")
    }))
    
    def clean_requisitionApproved(self):
        """ Validation for RequisitionApproved field in the AddRecruitment Form. """
        data = self.cleaned_data['requisitionApproved']
        if data == "False":
            raise ValidationError(_("Approval comments is required"), code = 'invalid')
        return data

class AdvertisementForm(forms.Form):
    """ Form creation - Advertisement Form """

    """ Options for Advertisement field in the AddAdvertisement Form. """
    ADVERTISEMENT_CHOICES = [
        ('True', _('Internal')),
        ('False', 'External'),
    ]

    advertisementType = forms.ChoiceField(
        label = _('Advertisement Type'),
        required = True, 
        widget = forms.RadioSelect,
        choices = ADVERTISEMENT_CHOICES,)

    closingDate = forms.DateField(
        label = _('Closing date'),
        required = True,
        widget = forms.DateInput(attrs = { 'placeholder': _("YYYY-MM-DD"), 'class': 'form-control'})
        )

    companyDescription = forms.CharField(
        label = _('Company description'),
        max_length = 500,
        required = False,
        widget = forms.Textarea(attrs = { 'placeholder': _("Enter your company description"), 'class': 'form-control', 'rows': '3'}))

    contactDetails = forms.CharField(
        label = _('Contact details'),
        max_length = 250,
        required = True,
        widget = forms.Textarea(attrs = { 'placeholder': _("Enter your contact details"), 'class': 'form-control', 'rows': '3'}))

    idealCandidate= forms.CharField(
        label = _('Ideal candidate'),
        max_length = 250,
        required = False,
        widget = forms.Textarea(attrs = { 'placeholder': _("Enter the characteristics of the ideal candidate "), 'class': 'form-control', 'rows': '3'}))

    jobDescription = forms.CharField(
        label = _('Job description'),
        max_length = 500,
        required = True,
        widget = forms.Textarea(attrs={ 'placeholder': _("Enter job description"), 'class': 'form-control', 'rows': '3'}))

    jobTitle = forms.CharField(
        label = _('Job title'),
        max_length = 250,
        required = True,
        widget = forms.TextInput(attrs={ 'placeholder': _("Enter job title"), 'class': 'form-control'}))

    location = forms.CharField(
        label = _('Location'),
        max_length = 250,
        required = True,
        widget = forms.TextInput(attrs = { 'placeholder': _("Enter work location"), 'class': 'form-control'}))

    salaryGuide = forms.CharField(
        label = _('Salary guide'),
        max_length = 250,
        required = True,
        widget = forms.Textarea(attrs = { 'placeholder': _("Enter salary guide"), 'class': 'form-control', 'rows': '3'}))

    comments = forms.CharField(
        label = _('Comments'),
        max_length = 500,
        required = False,
        widget = forms.Textarea(attrs = { 'placeholder': _("Enter aditional comments"), 'class': 'form-control', 'rows': '3'}))

    def clean_advertisementType(self):
        """ Validation for advertisementType field in the Advertisement Form. """
        data = self.cleaned_data['advertisementType']
        if data == "False":
            raise ValidationError(_("Company Description is required"), code = 'invalid')
        return data

class ReceiveCVsForm(forms.Form):
    """ Form creation - ApproveRequest Form """

    name = forms.CharField(
        label = _('Name'),
        max_length = 50,
        required = True,
        widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Enter your name")})
    )
    lastName = forms.CharField(
        label = _('Last Name'),
        max_length = 50,
        widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Enter your last name")})
    )
    cc = forms.CharField(
        label = _('CC'),
        max_length = 11,
        widget = forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _("Enter your #ID")})
    )
    email = forms.EmailField(
        label = _('E-mail'),
        max_length = 100,
        widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': _("Enter your E-mail")})
    )
    cellphone = forms.CharField(
        label = _('Cellphone'),
        max_length = 11,
        widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Enter your cellphone")})
    )
    homeAddress = forms.CharField(
        label = _('Home address'),
        max_length = 150,
        widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Enter your home address")})
    )
    age = forms.CharField(
        label = _('Age'),
        max_length = 3,
        widget = forms.NumberInput(attrs={'class': 'form-control', 'placeholder': _("Enter your age")})
    )
    cv = forms.FileField(
        widget = forms.FileInput(attrs={'class': 'form-control-file'})
    )

hr/templates/jobVacancyAdvertisement.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Job Vacancy" %}
{% endblock title %}

{% block content %}
<div class="container bg-white pt-2 pb-2 mt-3 mb-3">
    <div class="card card-header p-0 mb-0 mt-2">
        <h3>
            <a class="btn bg-gray btn-block text-left" data-toggle="collapse" data-target="#recruitmentRequest" aria-expanded="true" aria-controls="recruitmentRequest">
                <i class="fa fa-angle-down mr-1"></i>{% trans "Recruitment request" %}
            </a>
        </h3>
    </div>
    <div id="recruitmentRequest" class="collapse show">
        <div class="card card-body">
            <div class="row">
                <div class="form-group col row">
                    <label for="dateRequest" class="font-weight-bold col-sm-5 col-form-label">{% trans "Date of request" %}:</label>
                    <div class="col-sm-7 p-1">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="dateOfRequest" value="{{JVA.dateOfRequest}}">
                    </div>
                </div>
                <div class="form-group col row">
                    <label for="requester" class="font-weight-bold col-sm-3 col-form-label p-1">{% trans "Requester" %}:</label>
                    <div class="col-sm-9">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="requester" value="{{JVA.requester}}">
                    </div>
                </div>
                <div class="form-group col row">
                    <label for="departament" class="font-weight-bold col-sm-5 col-form-label p-1">{% trans "Departament" %}:</label>
                    <div class="col-sm-7">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="departament" value="{{JVA.departament}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col row">
                    <label for="startingDate" class="font-weight-bold col-sm-5 col-form-label">{% trans "Starting date" %}:</label>
                    <div class="col-sm-7 p-1">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="startingDate" value="{{JVA.startingDate}}">
                    </div>
                </div>
                <div class="form-group col row">
                    <label for="title" class="font-weight-bold col-sm-3 col-form-label p-1">{% trans "Title" %}:</label>
                    <div class="col-sm-9">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="title" value="{{JVA.title}}">
                    </div>
                </div>
                <div class="form-group col row">
                    <label for="vacancies" class="font-weight-bold col-sm-5 col-form-label p-1">{% trans "Number of vacancies" %}:</label>
                    <div class="col-sm-7">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="numberOfVacancies" value="{{JVA.numberOfVacancies}}">
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="responsabilities" class="font-weight-bold col-sm-2 col-form-label">{% trans "Responsabilities" %}:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext font-weight-light" id="responsabilities" value="{{JVA.responsabilities}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="location" class="font-weight-bold col-sm-2 col-form-label">{% trans "Location" %}:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext font-weight-light" id="location" value="{{JVA.location}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="comments" class="font-weight-bold col-sm-2 col-form-label">{% trans "Comments" %}:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext font-weight-light" id="comments" value="{{JVA.comments}}">
                </div>
            </div>
        </div>
    </div>
    <div class="card card-header p-0 mb-0 mt-2">
        <h3>
            <a class="btn bg-gray btn-block text-left" data-toggle="collapse" data-target="#ApprovalInformation" aria-expanded="true" aria-controls="ApprovalInformation">
                <i class="fa fa-angle-down mr-1"></i>{% trans "Approval Information" %}
            </a>
        </h3>
    </div>
    <div id="ApprovalInformation" class="collapse show">
        <div class="card card-body">
            <div class="row">
                <div class="form-group col row">
                    <label for="requisitionApproved" class="font-weight-bold col-sm-5 col-form-label">{% trans "Requisition Approval" %}:</label>
                    <div class="col-sm-7 p-1">
                        {% if JVA.requisitionApproved %} 
                            <input type="text" readonly class="form-control-plaintext font-weight-light" id="requisitionApproved" value="Yes">
                        {% else %}
                            <input type="text" readonly class="form-control-plaintext font-weight-light" id="requisitionApproved" value="No">
                        {% endif %}
                    </div>
                </div>
                <div class="form-group col row">
                    <label for="approvalsComments" class="font-weight-bold col-sm-3 col-form-label p-1">{% trans "Approvals Comments" %}:</label>
                    <div class="col-sm-9">
                        <input type="text" readonly class="form-control-plaintext font-weight-light" id="approvalsComments" value="{{JVA.approvalsComments}}">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <form id="jobD" method="post" action="">
            {% csrf_token %}
            <div class="card card-header p-0 mb-0 mt-2">
                <h3>
                    <a class="btn bg-gray btn-block text-left" data-toggle="collapse" data-target="#JobVacancyAdvertisement" aria-expanded="true" aria-controls="JobVacancyAdvertisement">
                        <i class="fa fa-angle-down mr-1"></i>{% trans "Recruitment Information" %}
                    </a>
                </h3>
            </div>
            <div id="JobVacancyAdvertisement" class="collapse show">
                <div class="card card-body">
                    <div class="row"> 
                        <div class="form-group col row">
                            <label for="id_advertisementType" class="font-weight-bold col-sm-1.5 col-form-label p-1">{% trans "Advertisement Type" %}:</label>
                            <div class="col-sm-5">
                                {{ form.advertisementType}}  
                            </div>
                        </div>
                        <div class="form-group col row">
                            <label for="id_closingDate" class="font-weight-bold col-sm-4 col-form-label p-1">{% trans "Closing date" %}:</label>
                            <div class="col-sm-7">
                                {{ form.closingDate }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_comments" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Comments" %}:</label>
                        <div class="col-sm-10">
                            {{ form.comments}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card card-header p-0 mb-0 mt-2">
                <h3>
                    <a class="btn bg-gray btn-block text-left" data-toggle="collapse" data-target="#adInformation" aria-expanded="true" aria-controls="adInformation">
                        <i class="fa fa-angle-down mr-1"></i>{% trans "Ad information" %}
                    </a>
                </h3>
            </div>
            <div id="adInformation" class="collapse show">
                <div class="card card-body">
                    <div class="form-group col row">
                        <label for="id_jobTitle" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Job Title" %}:</label>
                        <div class="col-sm-10">
                            {{ form.jobTitle}}
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_jobDescription" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Job Description" %}:</label>
                        <div class="col-sm-10">
                            {{ form.jobDescription }}
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_idealCandidate" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Ideal candidate" %}:</label>
                        <div class="col-sm-10">
                            {{ form.idealCandidate }}
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_location" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Location" %}:</label>
                        <div class="col-sm-10">
                            {{ form.location }}
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_salaryGuide" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Salary guide" %}:</label>
                        <div class="col-sm-10">
                            {{ form.salaryGuide }}
                        </div>
                    </div>
                    <div class="form-group col row">
                        <label for="id_contactDetails" class="font-weight-bold col-sm-2 col-form-label p-1">{% trans "Contact Details" %}:</label>
                        <div class="col-sm-10">
                            {{ form.contactDetails }}
                        </div>
                    </div>
                </div>
            </div>        
            <div id="btn_save" class="d-flex col-md-12 justify-content-center">
                <input type="submit" class="btn btn-md bg-gray w-25" value="{% trans 'Save' %}">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

hr/templates/recruitmentRequest.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Recruitment request" %}
{% endblock title %}

{% block content %}
    <div class="container bg-white pt-2 pb-2 mt-3 mb-3">
        <div class="card card-header p-0 mb-0 mt-2">
            <h3>
                <a class="btn bg-gray btn-block text-left" data-toggle="collapse" data-target="#recruitmentRequest" aria-expanded="true" aria-controls="recruitmentRequest">
                    <i class="fa fa-angle-down mr-1"></i>{% trans "Recruitment request" %}
                </a>
            </h3>
        </div>
        <div id="recruitmentRequest" class="collapse show">
            <div class="card card-body">
                <form id="jobD" method="post" action="">
                    {% csrf_token %}
                    {{ form|crispy}}
                    <div id="btn_save" class="d-flex col-md-12 justify-content-center">
                        <input type="submit" class="btn btn-md bg-gray w-25" value="{% trans 'Save' %}">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

hr/templates/requestList.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% trans "Request List" %}
{% endblock title %}

{% block content %}

<div class="site-section m-3 p-3">
    <div class="container bg-white">
        <div class="row mb-5">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">{% trans "Requester" %}</th>
                    <th scope="col">{% trans "Departament" %}</th>
                    <th scope="col">{% trans "Job Description" %}</th>
                    <th scope="col">{% trans "Responsabilities" %}</th>
                    <th scope="col">{% trans "Requisition Approved" %}</th>
                  </tr>
                </thead>
                <tbody>          
                {% for reqList in reqList %}
                  <tr>
                    <td>{{reqList.requester}}</td>
                    <td>{{reqList.departament}}</td>
                    <td>{{reqList.jobDescription}}</td>
                    <td>{{reqList.responsabilities}}</td>
                    <td>
                      {% if reqList.requisitionApproved is False %}
                        No
                      {% else %}
                        {% trans "Yes" %}
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>                   
        </div>
    </div>
</div>
{% endblock content %}