hr/urls.py
from django.urls import path
from hr import views
from django.conf import settings
from django.conf.urls.static import static

#general urls
app_name = 'hr'

""" URLs used in the HR application. """
urlpatterns = [
    path('recruitment/', views.RecruitmentView.as_view(), name='recruitment'),
    path('jobDescription/', views.JobDescriptionView.as_view(), name='jobDescription'),
    path('approveRequest/', views.ApproveRequestView.as_view(), name='approveRequest'),
    path('requestList/', views.RequestListView.as_view(), name='requestList'),
    path('jobVacancy/', views.JobVacancyAdvertisementView.as_view(), name='jobVacancy'),
    path('receiveCVs/', views.ReceiveCVsView.as_view(), name='receiveCV'),

    

]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# general imports
from django import views
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(),name="Home"),
    path('shop/', views.Shop.as_view(), name="shop")    
]

shop/urls.py
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'shop'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='summary'),   
    path('product/', views.ProductListView, name='product'),
    path('<str:parent_or_child>/<int:pk>', views.ProductListView, name='product_cat'),
    path('search/', views.search, name="search"), 
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path("payment_complete/", views.PaymentComplete, name="payment_complete"),
    path("payment_successful/", views.PaymentCompleteView.as_view(), name="payment_successful"),
]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import View
from . import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'user'
urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(),name='login'),
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup' ),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update' ),
    path(route='<str:username>/', view=views.UserDetailView.as_view(), name='detail' ),
]

if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from tabnanny import verbose
from django import forms
from django.forms import fields
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

from shop.models import OrderItem, Address
User = get_user_model()

#contact form class
class Contactf(forms.Form):
    Name = forms.CharField(label = _('Name'), 
        max_length=100, 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your Name")
    }))
    Last_name = forms.CharField(label = _('Last name'),
        max_length=100, 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your Last Name")
    }))
    Email = forms.EmailField(label = _('Email'), 
        widget=forms.TextInput(attrs={ 'placeholder': _("Your e-mail")
    }))
    Message = forms.CharField(label = _('Message'),
        widget=forms.Textarea(attrs={ 'placeholder': _("Your Message")
    }))

class AddToCartForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        fields = ['quantity']
        help_texts = {'quantity': None,}
        verbose_name = _('quantity')

class AddressForm(forms.Form):
    
    shipping_address_line_1 = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))
    shipping_zip_code = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))
    shipping_city = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))

    billing_address_line_1 = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))
    billing_zip_code = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))
    billing_city = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control',}))

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False,
        widget = forms.Select(attrs={'class': 'form-control',})
    )

    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False,
        widget = forms.Select(attrs={'class': 'form-control',})
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )

        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs


    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1", "Please fill in this field")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")

shop/views.py
import json
import datetime
from django.http import request, JsonResponse, response, Http404
from django.shortcuts import reverse, get_object_or_404, redirect, render
from django.views import generic
from django.core.mail import send_mail
from django.conf import settings 
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required

from paypalcheckoutsdk.orders import OrdersGetRequest
from shop.paypal import PayPalClient

from shop.forms import Contactf, AddToCartForm, AddressForm
from shop.models import Category, Product, OrderItem, SubCategory, Address, Order, Payment
from shop.utils import get_or_set_order_session



# Create your views here.


class ContactView(generic.FormView):
    form_class = Contactf
    template_name = "contact.html"

    def get_success_url(self):        
        return reverse("shop:contact")
    
    def form_valid(self, form):
        messages.info(
            self.request, "We have received your message ")
        Name = form.cleaned_data.get('Name')
        Last_name = form.cleaned_data.get('Last_name')
        Email = form.cleaned_data.get('Email')
        Message = form.cleaned_data.get('Message')

        full_message = f"""
            Message received from {Name},{Last_name}, {Email}
            ___________________________________


            {Message}
            """
        send_mail(
            subject="Message received by Contact Form",
            message=full_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.NOTIFY_EMAIL]
        )
        return super(ContactView, self).form_valid(form)

def search(request):
    if request.method == "POST":
        search = request.POST['search']
        product = Product.objects.filter(title__icontains=search)
        return render(request, 'product_list.html', {'search':search, 'product':product})
    else:
        return render(request, 'product_list.html', {})

def ProductListView(request, parent_or_child=None, pk=None):
    categories = Category.objects.filter(parent=None)
    
    if parent_or_child is None:
        products = Product.objects.all()
        paginator = Paginator(products, 6)
            
    elif parent_or_child == 'child':
        sub_cat= SubCategory.objects.get(pk=pk)
        products= sub_cat.product_set.all()
        paginator = Paginator(products, 6)
            
    elif parent_or_child == 'parent':
        products= []
        sub_cats= Category.objects.get(pk=pk).children.all()

        for sub_cat in sub_cats:
            prds = sub_cat.product_set.all()
            products += prds
        paginator = Paginator(products, 6)
            
    else:
        products = []        
          
    page = request.GET.get('page')
 
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products= paginator.page(paginator.num_pages)

    return render(
        request,
        'product_list.html',
        {'categories': categories, 'products': products, }
    )
    
class ProductDetailView(generic.FormView):
    template_name='product_detail.html'
    form_class = AddToCartForm
    
    def get_object(self):
        return get_object_or_404(Product, slug = self.kwargs["slug"])

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            order = get_or_set_order_session(self.request)
            product = self.get_object()
            form = self.form_class(request.POST)
            item_filter = order.items.filter(product = product)

            if form.is_valid():
                if item_filter.exists():
                    item = item_filter.first()
                    item.quantity += int(form.cleaned_data['quantity'])
                    item.save()
                    msg = "sumar item"
                    error = form.errors
                else:
                    new_item = form.save(commit=False)
                    new_item.product = product
                    new_item.order = order
                    new_item.save()
                    msg = "nuevo item"
                    error = form.errors
                response = JsonResponse({'mensaje':msg,'error':error})
                return response    
            else:
                msg = "form no valido"
                error = form.errors
                response = JsonResponse({'mensaje':msg,'error':error})
                print(form.errors)
                return response
    
    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context

class CartView(generic.TemplateView):
    template_name = "cart.html"
    def get_context_data(self, *args,**kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("shop:summary")

class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("shop:summary")

class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("shop:summary")

class CheckoutView(LoginRequiredMixin, generic.FormView):
    template_name = 'checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("shop:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')
        selected_billing_address = form.cleaned_data.get('selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type = 'S',
                user = self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type = 'B',
                user = self.request.user,
                address_line_1=form.cleaned_data['billing_address_line_1'],
                zip_code=form.cleaned_data['billing_zip_code'],
                city=form.cleaned_data['billing_city'],
            )
            order.billing_address = address

        order.save()
        messages.info(
            self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        return context

class PaymentView(generic.TemplateView):
    template_name = 'payment.html'
    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = "AW7Tl5AJ26bMhj7PR2eUtj0Kr4JD5q6GVqaDqq_D7YPQUeOAIbHledkYtDsiKcrbv1hFS9nkFVc3VG6_"
        context['order'] = get_or_set_order_session(self.request)
        return context

@login_required
def PaymentComplete(request):
    PPClient = PayPalClient()
    body = json.loads(request.body)
    data = body["orderID"]
    order = get_or_set_order_session(request)
    requestorder = OrdersGetRequest(data)
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value
    payment = Payment.objects.create(
        order=order,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        address1=response.result.purchase_units[0].shipping.address.address_line_1,
        city=response.result.purchase_units[0].shipping.address.admin_area_2,
        postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        country_code=response.result.purchase_units[0].shipping.address.country_code,
        total_paid=response.result.purchase_units[0].amount.value,
        order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order.ordered = True
    order.ordered_date = datetime.date.today()
    order.save()
    return JsonResponse("Payment completed!", safe=False)

class PaymentCompleteView(generic.TemplateView,LoginRequiredMixin):
    template_name = "payment_successful.html"

shop/templates/cart.html
{% extends "home.html" %}
{% load i18n%}
{% block title %}
    {% trans "Cart" %}
{% endblock title %}
{% block content %}

<div id="content" class="m-3 p-3">
    <div class="container bg-white ">
        <div class="row">
            <div id="checkout" class="col-lg-9">
                <div class="box">
                    <div class="content">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>{% trans "Image" %}</th>
                                        <th>{% trans "Product" %}</th>
                                        <th>{% trans "Price" %}</th>
                                        <th>{% trans "Quantity" %}</th>
                                        <th>{% trans "Total" %}</th>
                                        <th>{% trans "Actions" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <img src="{{ item.product.image.url }}" class="img-fluid">
                                        </td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black" >{{ item.product.title }}</h2>
                                        </td>
                                        <td>$ {{ item.product.get_price }}</td>
                                        <td>
                                            <div class="input-group"  style="max-width: 120px;">
                                                <div class="input-group-pretend ">
                                                    <a href="{% url 'shop:decrease-quantity' item.id %}"
                                                        class="btn btn-outline-primary"
                                                        style="margin-top: 0px;">
                                                        &minus;
                                                    </a>
                                                </div>
                                                <input type="text" class="form-control text-center"
                                                    value="{{ item.quantity }}"
                                                >
                                                <div class="input-group-append">
                                                    <a href="{% url 'shop:increase-quantity' item.id %}"
                                                        class="btn btn-outline-primary"
                                                        style="margin-top: 0px;">
                                                        &plus;
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            $ {{ item.get_total_item_price }}
                                        </td>
                                        <td>
                                            <a href="{% url 'shop:remove-from-cart' item.id %}"
                                                class="btn btn-outline-primary m-0">x</a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="6">{% trans "There are no items in your cart." %} 
                                            <a href="{% url 'shop:product' %}">
                                                {% trans "Continue Shopping" %}
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="4">Total</th>
                                        <th>$ {{ order.get_subtotal }}</th>
                                    </tr>
                                </tfoot>
                            </table>
                            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row mb-5">
                                    <div class="col-md-12">
                                        <a class="btn btn-outline-primary btn-sm btn-block"
                                        href="{% url 'shop:product' %}">{% trans "Continue Shopping" %}</a>
                                    </div>
                                </div>
                            </div>               
                        </div>
                    </div>
                </div>
            </div>

            {% if order.items.count > 0 %}               
                <div class="col-lg-3">
                    <div id="order-summary" class="box mb-4 p-0">
                        <div class="box-header mt-0 bg-white">
                            <h3>{% trans "Order summary" %}</h3>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Subtotal</td>
                                        <th>$ {{ order.get_subtotal }}</th>
                                    </tr>
                                    <tr>
                                        <td>{% trans "Shipping Cost" %}</td>
                                        <th>$ 0</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th>$ {{ order.get_total }}</th>
                                    </tr>
                                </tbody>
                            </table>                            
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{% url 'shop:checkout' %}" class="btn btn-outline-primary btn-lg py-3 btn-block">{% trans "Proceed to Checkout" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

shop/templates/contact.html
{% extends "indexx.html" %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %}
    {% trans "Contact" %}
{% endblock title %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'Home' %}">{% trans "Home" %}</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">{% trans "Contact" %}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">{% trans "Get in touch" %}</h2>
            </div>

            <div class="col-md-7">
                <form method="POST"> 
                    {% csrf_token %}
                    {{ form|crispy}}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="{% trans 'Submit message' %}"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

shop/templates/payment.html
{% extends "home.html" %}
{% load i18n %}

{% block title %}
{% trans " Payment" %}
{% endblock title %}

{% block content %}

<div class="site-section p-3">
    <div class="container bg-white p-3">
        <div class="row">
            <div class="col-md-7 mb-md-0">
                <h2 class="h3 mb-3 text-black text-center">{% trans "Select Payment Method" %}</h2>
                <hr />
                <div id="paypal-button-container" class="pt-4"></div>
            </div>
            <div class="col-md-5">
                <div class="row mb-5">
                    <div class="col-md-12">
                        <h2 class="h3 mb-3 text-black text-center">{% trans "Your Order" %}</h2>
                        <hr>
                        <div class="p-1">
                            <table class="table site-block-order-table mb-2">
                                <thead>
                                    <th>{% trans "Product" %}</th>
                                    <th>{% trans "Total" %}</th>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                    <tr>
                                        <td>
                                            {{ item.product.title }}
                                            <strong class="mx-2">x</strong> {{ item.quantity }}
                                        </td>
                                        <td>
                                            $ {{ item.get_total_item_price }}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td><strong class="text-black font-weight-bold">{% trans "Subtotal" %}</strong>
                                        </td>
                                        <td>$ {{ order.get_subtotal }}</td>
                                    </tr>
                                    <tr>
                                        <td><strong>{% trans "Order Total" %}</strong></td>
                                        <td><strong class="text-black font-weight-bold">$ {{order.get_total}}</strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script
    src="https://www.paypal.com/sdk/js?client-id=AW7Tl5AJ26bMhj7PR2eUtj0Kr4JD5q6GVqaDqq_D7YPQUeOAIbHledkYtDsiKcrbv1hFS9nkFVc3VG6_"></script>
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
    function initPayPalButton() {
        paypal.Buttons({
            style: {
                shape: 'pill',
                color: 'blue',
                layout: 'vertical',
                label: 'paypal',

            },
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        "amount": {
                            "currency_code": "USD",
                            "value": '{{order.get_total|stringformat:".2f"}}'
                        }
                    }]
                });
            },
            onApprove: function (data) {
                var url = "{% url 'shop:payment_complete' %}"
                return fetch(url, {
                    method: 'POST',
                    headers: {
                        'content-type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({
                        orderID: data.orderID
                    })
                }).then(function () {
                    location.href = '{% url "shop:payment_successful" %}';
                })
            },
        }).render('#paypal-button-container');
    }
    initPayPalButton();
</script>

{% endblock content %}

shop/templates/payment_successful.html
{% extends "home.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Payment Successful" %}{%endblock title%}

{% block content %}

<div id="content" class=" m-3 p-3 p-bottom-2">
  <div class="payment border">
    <div class="payment_header">
       <div class="check"><i class="fa fa-check" aria-hidden="true" style="color:rgba(79, 191, 168, 0.9)"></i></div>
    </div>
  <div class="container bg-white p-3">
    <h1 class="text-center"> {% trans "Payment Successful" %} </h1>
    <p class="text-center">{% trans "Thank you for your purchase" %}</p>
    <div class="d-flex justify-content-center p-3" >
      <a href="{% url 'main:shop'%}" class="btn btn-primary btn-md py-3 w-25 rounded" >{% trans "Go to Home" %}</a>
    </div>  
  </div>  
</div>
{% endblock %}



   