hr/urls.py
from django.urls import path
from hr import views
from django.conf import settings
from django.conf.urls.static import static

#general urls
app_name = 'hr'

""" URLs used in the HR application. """
urlpatterns = [
    path('recruitment/', views.RecruitmentView.as_view(), name='recruitment'),
    path('jobDescription/', views.JobDescriptionView.as_view(), name='jobDescription'),
    path('approveRequest/', views.ApproveRequestView.as_view(), name='approveRequest'),
    path('requestList/', views.RequestListView.as_view(), name='requestList'),
    path('jobVacancy/', views.JobVacancyAdvertisementView.as_view(), name='jobVacancy'),
    path('receiveCVs/', views.ReceiveCVsView.as_view(), name='receiveCV'),

    

]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# general imports
from django import views
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(),name="Home"),
    path('shop/', views.Shop.as_view(), name="shop")    
]

shop/urls.py
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'shop'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='summary'),   
    path('product/', views.ProductListView, name='product'),
    path('<str:parent_or_child>/<int:pk>', views.ProductListView, name='product_cat'),
    path('search/', views.search, name="search"), 
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path("payment_complete/", views.PaymentComplete, name="payment_complete"),
    path("payment_successful/", views.PaymentCompleteView.as_view(), name="payment_successful"),
]
if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import View
from . import views
from django.conf import settings
from django.conf.urls.static import static
#general urls
app_name = 'user'
urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(),name='login'),
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup' ),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update' ),
    path(route='<str:username>/', view=views.UserDetailView.as_view(), name='detail' ),
]

if not settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from calendar import c
from django.shortcuts import render
from django.views import generic
from shop.models import Product
from article.models import Article

class Shop(generic.ListView):
    template_name = "indexx.html"
    queryset = Product.objects.all()

class Home(generic.ListView):
    template_name = "home.html"
    queryset = Article.objects.all().order_by("-id")
    paginate_by = 6
    def get_context_data(self, **kwargs):
       context = super(Home, self).get_context_data(**kwargs)
       context['publish_list'] = Article.objects.all().order_by("-id")[:5]
       context['product_list'] = Product.objects.all()
       return context

main/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome CSS-->
  <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
  <!-- Google fonts - Roboto-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
  <!-- Bootstrap Select-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
  <!-- owl carousel-->
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <!-- Favicon and apple touch icons-->
  <link rel="shortcut icon" href="{% static 'img/logo.jpg' %}" type="image/x-icon"><!-- Imagene tab-->

  <!-- Tweaks for older IEs-->
  <!--[if lt IE 9]><script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script><script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-FK3X2BNB0E"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-FK3X2BNB0E');
  </script>
</head>

<body class="bg-body">
  <div id="all">
    <!-- Top bar-->
    <div class="top-bar">
      <div class="container">
        <div class="row d-flex align-items-center" style="width: 1280px;">
          <div class="col-md-4 d-md-block d-none">
            <p> {% trans "Contactanos al +57 (608) 678 2084 o lalicoadmin@gmail.com" %} </p>
          </div>

          <div class="col-md-6">
            <div class="d-flex justify-content-md-end justify-content-between">
              {% if not request.user.is_authenticated %}
              <div class="login">
                <a href="#" data-toggle="modal" data-target="#login-modal" class="login-btn">
                  <i class="fa fa-sign-in"></i><span class="d-none d-md-inline-block">{% trans "Sign In" %}</span>
                </a>
                <a href="{% url 'user:signup' %}" class="signup-btn">
                  <i class="fa fa-user"></i>
                  <span class="d-none d-md-inline-block">{% trans "Sign Up" %}</span>
                </a>
              </div>
              {% else %}
              {% if request.user.is_superuser %}
              <a href="#"> {{ user.username }} &nbsp; </a>
              <div class="header-menu">
                <div class="user-area dropdown float">
                  <a href="#" class="dropdown-toggle active " data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="fa fa-user " aria-hidden="true"> </i>
                  </a>
                  <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="{% url 'admin:index' %}"><i class="fa fa -cog"></i>{% trans "Administrate"
                      %} </a>
                    <a class="nav-link" href="{% url 'user:logout' %}"><i class="fa fa-power -off"></i> {% trans
                      "Logout" %}</a>
                  </div>
                </div>
              </div>
              {% else %}
              <a href="#"> {{ user.username }} &nbsp; </a>
              <div class="header-menu">
                <div class="user-area dropdown float">
                  <a href="#" class="dropdown-toggle active " data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="fa fa-user " aria-hidden="true"> </i>
                  </a>
                  <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="{% url 'user:detail' request.user.username %}"><i
                        class="fa fa -cog"></i>{% trans "My account" %}</a>
                    <a class="nav-link" href="{% url 'user:logout' %}"><i class="fa fa-power -off"></i>{% trans "Logout"
                      %}</a>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endif %}
              <ul class="social-custom list-inline">
                <li class="list-inline-item"><a href="https://www.facebook.com/encisosystems/"><i
                      class="fa fa-facebook"></i></a>
                </li>
                <li class="list-inline-item"><a href="https://www.instagram.com/encisosystemsco/"><i
                      class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="https://www.twitter.com/encisosystems/"><i
                      class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="https://www.youtube.com/c/EncisoSystems"><i
                      class="fa fa-youtube"></i></a></li>
                <li class="list-inline-item"><a href="https://www.linkedin.com/company/encisosystems/"><i
                      class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-2 justify-content-md-end">
            <form action="/i18n/setlang/" method="post" style="display: inline;">
              {% csrf_token %}
              <div style="display: inline;">
                <select class="text-white" name="language" onchange="javascript:form.submit()"
                  style="border: none; background: #555;">
                  {% for lang in LANGUAGES %}
                  <option value="{{ lang.0 }}" {% ifequal LANGUAGE_CODE lang.0 %} selected="selected" {% endifequal %}>
                    {{ lang.1 }}</option>
                  {% endfor %}
                </select>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Top bar end-->
    <!-- Login Modal-->
    <div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modalLabel" aria-hidden="true"
      class="modal fade">
      <div role="document" class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 id="login-modalLabel" class="modal-title">{% trans "Customer Login" %}</h4>
            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span
                aria-hidden="true">×</span></button>
          </div>
          <div class="modal-body">
            <form method="POST" action="{% url 'user:login' %}">
              {% csrf_token %}

              <div class="form-group ">
                {% if form.error_messages %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <strong>{% trans "Warning" %}: </strong> {{ form.get_invalid_login_error }}
                </div>
                {% endif %}
                <input class="form-control" type="text" placeholder="{% trans 'Username' %}" name="username" />
              </div>

              <div class="form-group">
                <input id="password_modal" class="form-control" type="password" placeholder="{% trans 'Password' %}"
                  name="password" />
              </div>


              <button class="btn btn-primary btn-block mt-5" type="submit">{% trans "Sign in" %}!</button>
            </form>
            <p class="text-center text-muted">{% trans "Not registered yet?" %}</p>
            <p class="text-center text-muted">
              <a href="{% url 'user:signup' %}">
                <strong>{% trans "Register now" %}!</strong>
              </a> {% trans "It is easy and done in 1 minute and gives you access to special discounts and much more"
              %}!
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Login modal end-->
    {% block navbar %}

    {% endblock navbar %}

    {% block content %}

    {% endblock content %}

    <!-- FOOTER -->
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <h4 class="h4">{% trans "Contact" %}</h4>
            <hr>
            <ul id="contact" class="list-unstyled">
              <li id="c-address">
                <strong>{% trans "Address:" %}</strong>
                <p class="m-0 d-inline"> Calle 35B # 19D - 40</p>
                <p class="m-0">Villavicencio, Colombia</p>
              </li>
              <li id="c-phone">
                <strong>{% trans "Phone:" %}</strong>
                <p class="m-0 d-inline"> +57 (608) 678 2084</p>
              </li>
              <li id="c-cell">
                <strong>{% trans "Cell:" %}</strong>
                <p class="m-0 d-inline"> +57 320 880 8381</p>
              </li>
              <li id="c-email">
                <strong>{% trans "Email:" %}</strong> <a href="mailto:info@encisosystems.com">info@encisosystems.com</a>
              </li>
            </ul>
            <hr class="d-block d-lg-none">
          </div>
          <div class="col-lg-2">
            <h4 class="h4">{% trans "Social Media" %}</h4>
            <hr>
            <ul class="list-unstyled" id="socialMedia">
              <li id="sm-facebook">
                <a href="https://www.facebook.com/encisosystems/"> Facebook </a>
              </li>
              <li id="sm-instagram">
                <a href="https://www.instagram.com/encisosystemsco/"> Instagram </a>
              </li>
              <li id="sm-twitter">
                <a href="https://www.twitter.com/encisosystems/"> Twitter </a>
              </li>
              <li id="sm-linkedin">
                <a href="https://www.linkedin.com/company/encisosystems/"> LinkedIn </a>
              </li>
              <li id="sm-youtube">
                <a href="https://www.youtube.com/c/EncisoSystems"> Youtube </a>
              </li>
            </ul>
            <hr class="d-block d-lg-none">
          </div>
          <div class="col-lg-4">
            <h4 class="h4">{% trans "Legal Notice" %}</h4>
            <hr>
            <p>
              Enciso Systems SAS is a simplified stock company, NIT 901390798 - 9. Send your legal notifications to
              <br><a href="mailto:legal@encisosystems.com"> legal@encisosystems.com </a>
            </p>
            <hr class="d-block d-lg-none">
          </div>
          <div class="col-lg-2">
            <h4 class="h4">{% trans "Help" %}</h4>
            <hr>
            <ul id="help" class="list-unstyled">
              <li id="h-contact">
                <a href="#"> Contact </a>
              </li>
              <li id="h-people">
                <a href="#"> People </a>
              </li>
              <li id="g-terms">
                <a href="/terms-and-conditions/"> Terminos y Conditions </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="copyrights p-2">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <h4 class="h4"> Memberships </h4>
              <p class="float-right">
                <a href="https://fedesoft.org/">
                  <img alt="Fedesoft Logo" src="/static/img/logo-fedesoft-50.png" width="180" height="53">
                </a>
                <br>&copy;{% now "Y" %}. LaLico
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!-- Javascript files-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
  <script src="{% static 'vendor/waypoints/lib/jquery.waypoints.min.js' %}"> </script>
  <script src="{% static 'vendor/jquery.counterup/jquery.counterup.min.' %}js"> </script>
  <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
  <script src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.scrollto/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'js/front.js' %}"></script>
  <script src="{% static 'js/product_detail.js' %}"></script>

</body>

</html>

main/templates/home.html
{% extends "base.html" %}
{% load static i18n%}
{% block title %}
  {% trans "Home | LaLico" %}
{% endblock title %}

{% block navbar %}
 <!-- Navbar Start-->
<header class="nav-holder make-sticky">
    <div id="navbar" role="navigation" class="navbar navbar-expand-lg">
        <div class="col-lg-2 col-md-3 col-sm-3">
            <a href="{% url 'Home' %}" class="navbar-brand home">
                <img width="80" height="80" src="{% static 'img/logo.jpg' %}" alt="LaLico logo" class="d-none d-md-inline-block">
                <img width="80" height="80" src="{% static 'img/logo.jpg' %}" alt="LaLico logo" class="d-inline-block d-md-none">
                <span class="sr-only">{% trans "Enciso - go to homepage" %}</span>
            </a>
        </div>
        <!-- Navbar -->
        <div class="col-lg-10 col-md-9 col-sm-9 p-0">
            <div class="container p-0 ml-1">
                <!-- Button collapse-->
                <button type="button" data-toggle="collapse" data-target="#navigation"
                    class="navbar-toggler btn-template-outlined"><span class="sr-only">{% trans "Toggle navigation"
                        %}</span><i class="fa fa-align-justify"></i>
                </button>
                <div id="navigation" class="navbar-collapse collapse">
                    <!-- Navbar menus-->
                    {% load menus %}
                    {% init_menu 'Main Menu' as main_menu %}
                    {% render_menu main_menu main %}
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Navbar End-->
{% endblock navbar %}

{% block content %}

<!-- imagen de fondo -->
<section class="mt-3">
    <div class="container bg-white">
        <!-- Carousel Start-->
        <div class="home-carousel">
            <div class="homepage owl-carousel">
                {% for article in publish_list %}
                <div class="item" style="height: 500px;">
                    <div class="row">
                        <div class="col-md-12" style="overflow: hidden;">
                            <a href="{{ article.get_absolute_url }}">
                                <img class="img-top img-fluid img-responsive "
                                    style="width: 1200px; height: auto; left: 0px; top: 0px;"
                                    src="{{ article.image.url }}" alt="{{ article.name }}">
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- Carousel End-->
    </div>
</section>
<section class="bar bg-body">
  <div class="container bg-white">
    <div class="heading text-center"><br>
      <h2>{% trans "ARTICLE"%}</h2>
    </div>
    <div class="container ">    
        <div class="row mb-5">
            {% for article in object_list %}
            <div class="col-lg-12 col-md-12 col-ms-12 mb-2 mt-3" data-aos='fade-up'>
                <div class="card border-secondary ">
                    <div class="card-header">
                        <a href="{{ article.get_absolute_url }}">
                            <h3 class="card-title">{{ article.name }} </h3>
                        </a> 
                    </div>                                      
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3">
                                <figure class="block-4-image ">
                                    <a href="{{ article.get_absolute_url }}">
                                        <img class="card-img-top" width="250" height="150"
                                            src="{{ article.image.url }}" alt="{{ article.name }}">
                                    </a>
                                </figure>
                            </div>
                            <div class="col-9">
                                <p class="card-text:justify"> {{ article.abstract|safe }} </p>
                                <a href="{{ article.get_absolute_url }}" class="btn btn-primary">{% trans "Read more" %}</a>
                            </div>
                        </div>                      
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div> 
                  
            {% if page_obj.paginator.num_pages > 1%}
                <div class="d-flex justify-content-center">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                &lang; {% trans "Previous" %}</a></li>
                        {% endif %}
                        {% for page in page_obj.paginator.page_range %}
                            {% if forloop.last and page != page_obj.number and page_obj.paginator.num_pages > 7 %} 
                                {% if page_obj.next_page_number != page_obj.paginator.num_pages%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.number | add:1}}">...</a>
                                </li>
                                {% endif %}
                            <li class="page-item">
                                    <a class="page-link" href="?page={{paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a>
                            </li>
                            {% endif %}
                            {% if page == page_obj.number and page > 7 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page | add:-1 }}">...</a>
                            </li>    
                            {% endif %}
                            {% if page < 7 or page == page_obj.number %}
                            <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                            </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item d-none d-sm-block">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %} &rang;</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="d-flex justify-content-center d-sm-none">            
                    {% if page_obj.has_previous %}
                        <span class="page-item"><a  class="page-link" href="?page={{ page_obj.previous_page_number }}">&lang; {% trans "Previous" %}</a></span>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <span class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %} &rang;</a></span>
                    {% endif %}
                    <br>
                    <br>
                </div>
            {% endif %}
        </div> 
    </div>
  </div>
</section>

{% endblock content %}

main/templates/indexx.html
{% extends "base.html" %}
{% load static i18n%}
{% block title %}
  {% trans "Tienda Lico" %}
{% endblock title %}

{% block navbar %}
 <!-- Navbar Start-->
 <header class="nav-holder make-sticky">
  <div id="navbar" role="navigation" class="navbar navbar-expand-lg">
    <div class="col-lg-2 col-md-3 col-sm-3">
      <a href="{% url 'main:shop' %}" class="navbar-brand home">
        <img width="80" height="80" src="{% static 'img/logo.jpg' %}" alt="Lico logo" class="d-none d-md-inline-block">
        <img width="80" height="80" src="{% static 'img/logo.jpg' %}" alt="Lico logo" class="d-inline-block d-md-none">
        <span class="sr-only">{% trans "Enciso - go to homepage" %}</span>
      </a>
    </div>
    <!-- Navbar -->
    <div class="col-lg-9 col-md-8 col-sm-8 p-0">
      <div class="container p-0">
        {% load menus %}
        {% init_menu 'Shop Menu' as shop_menu %}            
        <!-- Button collapse-->            
        <button type="button" data-toggle="collapse" data-target="#navigation"
          class="navbar-toggler btn-template-outlined"><span class="sr-only">{% trans "Toggle navigation" %}</span><i
          class="fa fa-align-justify"></i>
        </button>          
        <div id="navigation" class="navbar-collapse collapse">
          <!--Search -->            
          <div class="form-group w-50 m-1">
            <form class="d-flex" method=POST action="{% url 'shop:search' %}">
              {% csrf_token %}
              <input type="text" class="form-control" placeholder="{% trans 'Search' %}" name="search">
              <div class="input-group-append">
                <button class="btn btn-outline-primary" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </form>                
          </div> 
          <!-- Navbar menus-->          
          {% render_menu shop_menu main %}            
        </div>                     
      </div>
    </div>
    <!-- Cart Item -->
    {% load cart_template_tags %}
    <div class="col-lg-1 col-md-1 col-sm-1">
      <a href="{% url 'shop:summary' %}" class="site-cart float-right">
        <span><i class="fa fa-shopping-cart"></i></span>
        <span class="count"> {{request|cart_item_count}} </span>
      </a>
    </div>        
  </div>
</header>
<!-- Navbar End-->
{% endblock navbar %}

{% block content %}

<!-- imagen de fondo -->
<section >
  <div class="container">
    <!-- Carousel Start-->
    <div class="home-carousel">
      <div class="dark-mask mask-primary"></div>
      <div class="container">
        <div class="homepage owl-carousel">
          <div class="item">
            <div class="row">
              <div class="col-md-5 text-right">
                <!--<p><img src="{% static 'img/logo.png' %}" alt="" class="ml-auto"></p>-->
                <h1>{% trans "LOS MEJORES LICORES" %}</h1>
                <p>{% trans "Disfruta de los mejores licores" %}<br>{% trans "A los mejores precios" %}</p>
              </div>
              <div class="col-md-7"><img src="{% static 'img/licores.png' %}" alt="" class="img-fluid"></div>
            </div>
          </div>
          <div class="item">
            <div class="row">
              <div class="col-md-7 text-center"><img src="{% static 'img/licores.png' %}" alt="" class="img-fluid"></div>
              <div class="col-md-5">
                <h1>{% trans "Licores de todos los tipos" %}</h1>
                <!-- <ul class="list-unstyled">
                  <li>Sliders and carousels</li>
                  <li>4 Header variations</li>
                  <li>Google maps, Forms, Megamenu, CSS3 Animations and much more</li>
                  <li>+ 11 extra pages showing template features</li>
                </ul>-->
              </div>
            </div>
          </div>

          <div class="item">
            <div class="row">
              <div class="col-md-7"><img src="{% static 'img/licores.png' %}" alt="" class="img-fluid">
              </div>
              <div class="col-md-5">
                <h1>{% trans "Compre el Licor de su agrado"%}</h1>
                <!--<ul class="list-unstyled">
                  <li>7 preprepared colour variations.</li>
                  <li>Easily to change fonts</li>
                </ul>-->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Carousel End-->
  </div>
</section>
<section class="bar bg-body">
  <div class="container bg-white">
    <div class="heading text-center"><br>
      <h2>{% trans "Productos"%}</h2>
    </div>

    <div class="container ">
      <div class="row mb-5">
    
        {% for product in object_list %}
        <div class="col-lg-4 col-md-6 col-ms-6 mb-2 mt-5" data-aos='fade-up'>
          <div class="d-flex align-items-start justify-content-center" >
            <figure class="block-4-image ">
              <a href="{{ product.get_absolute_url }}"><img class="img-fluid img-responsive" style="height: 250px;" src="{{ product.image.url }}" alt="{{ product.title }}"> </a>
            </figure>
          </div>         
    
          <div class="d-block justify-content-start block-4-text p-2">
            <a href="{{ product.get_absolute_url }}">
              <h3>{{ product.title }}</h3>
            </a>
            <p class="mb-0">{% trans "Price" %}: {{ product.price }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<section class="bar bg-clients">
  <div class="container">
    <div class="heading text-center">
      <h2>{% trans "Nuestros Clientes" %}</h2>
    </div>
    <ul class="list-unstyled owl-carousel customers no-mb">
      <li class="item"><img src="{% static 'img/customer-1.png' %}" alt="" class="img-fluid"></li>
      <li class="item"><img src="{% static 'img/customer-2.png' %}" alt="" class="img-fluid"></li>
      <li class="item"><img src="{% static 'img/customer-3.png' %}" alt="" class="img-fluid"></li>
      <li class="item"><img src="{% static 'img/customer-4.png' %}" alt="" class="img-fluid"></li>
      <li class="item"><img src="{% static 'img/customer-5.png' %}" alt="" class="img-fluid"></li>
      <li class="item"><img src="{% static 'img/customer-6.png' %}" alt="" class="img-fluid"></li>
    </ul>
  </div>
</section>
{% endblock content %}